BASEDIR=$1
PORTTOFORWARD=$2
SCRIPTDIR=$(dirname "$0")
source $SCRIPTDIR/../ssh/vars.sh
if [ -z "$PORTTOFORWARD" ]; then
  PORTTOFORWARD=$((22000+$SOURCEINFORMATIONBUCKETID))
fi
echo make $PORTTOFORWARD available on local
ssh $SSH_OPTIONS_IDENTITY_FILE $SSH_OPTIONS_CLI -v -NL "$PORTTOFORWARD:localhost:$PORTTOFORWARD" $SSHPORT $SSHUSERNAME_AT_MACHINE