#!/bin/bash
SCRIPTNAME=upload
BASEDIR=$1
LOCALPATH=$2
REMOTEPATH=$3
SCRIPTDIR=$(dirname "$0")
echo [$SCRIPTNAME] start
source $SCRIPTDIR/../ssh/vars.sh
REMOTEHOMEDIR=`ssh -i $BASEDIR/config/id_rsa $USERNAME@$MACHINEADDR pwd`;
LOCALHOMEDIR=`echo $HOME`;
REMOTEDIR="${REMOTEPATH/"~"/$REMOTEHOMEDIR}"
LOCALDIR="${LOCALPATH/"~"/$LOCALHOMEDIR}"
echo [$SCRIPTNAME] rsync local:$LOCALDIR to remote:$REMOTEDIR
rsync -av -e "ssh -i $BASEDIR/config/id_rsa $SSHPORT" $LOCALDIR $SSHUSERNAME_AT_MACHINE:$REMOTEDIR
